#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("Lab7Fragments.Resource", IsApplication=true)]

namespace Lab7Fragments
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int icon = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050001
			public const int details = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int titles_fragment = 2131034112;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int activity_main = 2130903040;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040000
			public const int ApplicationName = 2130968576;
			
			// aapt resource value: 0x7f040008
			public const int apr = 2130968584;
			
			// aapt resource value: 0x7f04000c
			public const int aug = 2130968588;
			
			// aapt resource value: 0x7f040001
			public const int blankLine = 2130968577;
			
			// aapt resource value: 0x7f040014
			public const int cm = 2130968596;
			
			// aapt resource value: 0x7f040010
			public const int dec = 2130968592;
			
			// aapt resource value: 0x7f040006
			public const int feb = 2130968582;
			
			// aapt resource value: 0x7f04001a
			public const int fri = 2130968602;
			
			// aapt resource value: 0x7f040013
			public const int ft = 2130968595;
			
			// aapt resource value: 0x7f040003
			public const int heading = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int headingAlt = 2130968580;
			
			// aapt resource value: 0x7f040012
			public const int high = 2130968594;
			
			// aapt resource value: 0x7f040005
			public const int jan = 2130968581;
			
			// aapt resource value: 0x7f04000b
			public const int jul = 2130968587;
			
			// aapt resource value: 0x7f04000a
			public const int jun = 2130968586;
			
			// aapt resource value: 0x7f040002
			public const int label = 2130968578;
			
			// aapt resource value: 0x7f040011
			public const int low = 2130968593;
			
			// aapt resource value: 0x7f040007
			public const int mar = 2130968583;
			
			// aapt resource value: 0x7f040009
			public const int may = 2130968585;
			
			// aapt resource value: 0x7f040016
			public const int mon = 2130968598;
			
			// aapt resource value: 0x7f04000f
			public const int nov = 2130968591;
			
			// aapt resource value: 0x7f04000e
			public const int oct = 2130968590;
			
			// aapt resource value: 0x7f04001b
			public const int sat = 2130968603;
			
			// aapt resource value: 0x7f04000d
			public const int sep = 2130968589;
			
			// aapt resource value: 0x7f04001c
			public const int stationHeading = 2130968604;
			
			// aapt resource value: 0x7f040015
			public const int sun = 2130968597;
			
			// aapt resource value: 0x7f040019
			public const int thu = 2130968601;
			
			// aapt resource value: 0x7f040017
			public const int tue = 2130968599;
			
			// aapt resource value: 0x7f040018
			public const int wed = 2130968600;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
