#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18033
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("MultiScreen.Resource", IsApplication=true)]

namespace MultiScreen
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050001
			public const int ScreenOneButton = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int ScreenOneText = 2131034112;
			
			// aapt resource value: 0x7f050003
			public const int ScreenTwoButton = 2131034115;
			
			// aapt resource value: 0x7f050002
			public const int ScreenTwoText = 2131034114;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int ScreenOne = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int ScreenTwo = 2130903041;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040004
			public const int ErrorString = 2130968580;
			
			// aapt resource value: 0x7f040002
			public const int Screen1Button = 2130968578;
			
			// aapt resource value: 0x7f040000
			public const int Screen1DefaultText = 2130968576;
			
			// aapt resource value: 0x7f040003
			public const int Screen2Button = 2130968579;
			
			// aapt resource value: 0x7f040001
			public const int Screen2DefaultText = 2130968577;
			
			// aapt resource value: 0x7f040005
			public const int app_name = 2130968581;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
