#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("TabbedWalkThrough.Resource", IsApplication=true)]

namespace TabbedWalkThrough
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Animation
		{
			
			// aapt resource value: 0x7f040000
			public const int rotate_centre = 2130968576;
			
			static Animation()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Animation()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int blank = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int Die1 = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int Die2 = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int Die3 = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int Die4 = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int Die5 = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int Die6 = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int ic_tab_home = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int ic_tab_home_grey = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int ic_tab_home_white = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int ic_tab_play = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int ic_tab_play_grey = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int ic_tab_play_white = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int icon = 2130837517;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060000
			public const int CurrentGameScore = 2131099648;
			
			// aapt resource value: 0x7f060008
			public const int CurrentRolls = 2131099656;
			
			// aapt resource value: 0x7f060006
			public const int CurrentScore = 2131099654;
			
			// aapt resource value: 0x7f060007
			public const int CurrentTally = 2131099655;
			
			// aapt resource value: 0x7f060005
			public const int Description = 2131099653;
			
			// aapt resource value: 0x7f06000a
			public const int Die = 2131099658;
			
			// aapt resource value: 0x7f060001
			public const int GamesPlayed = 2131099649;
			
			// aapt resource value: 0x7f06000c
			public const int Pass = 2131099660;
			
			// aapt resource value: 0x7f06000b
			public const int Roll = 2131099659;
			
			// aapt resource value: 0x7f060009
			public const int WhoseMove = 2131099657;
			
			// aapt resource value: 0x7f060002
			public const int WinsLosses = 2131099650;
			
			// aapt resource value: 0x7f060003
			public const int playCompBtn = 2131099651;
			
			// aapt resource value: 0x7f060004
			public const int playPlayerBtn = 2131099652;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Home = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int PigTabActivity = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Play = 2130903042;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050000
			public const int app_name = 2131034112;
			
			// aapt resource value: 0x7f050016
			public const int cTurnTotal = 2131034134;
			
			// aapt resource value: 0x7f05000f
			public const int compMove = 2131034127;
			
			// aapt resource value: 0x7f05000c
			public const int compScore = 2131034124;
			
			// aapt resource value: 0x7f05001a
			public const int compWon = 2131034138;
			
			// aapt resource value: 0x7f050009
			public const int currentGameScore = 2131034121;
			
			// aapt resource value: 0x7f050011
			public const int currentRolls = 2131034129;
			
			// aapt resource value: 0x7f050008
			public const int currentScore = 2131034120;
			
			// aapt resource value: 0x7f050010
			public const int currentTally = 2131034128;
			
			// aapt resource value: 0x7f05001c
			public const int description = 2131034140;
			
			// aapt resource value: 0x7f050004
			public const int gamesPlayed = 2131034116;
			
			// aapt resource value: 0x7f050001
			public const int heading = 2131034113;
			
			// aapt resource value: 0x7f050007
			public const int losses = 2131034119;
			
			// aapt resource value: 0x7f05001b
			public const int p2Won = 2131034139;
			
			// aapt resource value: 0x7f050017
			public const int pTurnTotal = 2131034135;
			
			// aapt resource value: 0x7f050014
			public const int pass = 2131034132;
			
			// aapt resource value: 0x7f05000e
			public const int player2Move = 2131034126;
			
			// aapt resource value: 0x7f05000b
			public const int player2Score = 2131034123;
			
			// aapt resource value: 0x7f05000d
			public const int playerMove = 2131034125;
			
			// aapt resource value: 0x7f05000a
			public const int playerScore = 2131034122;
			
			// aapt resource value: 0x7f050012
			public const int roll1 = 2131034130;
			
			// aapt resource value: 0x7f050013
			public const int roll2 = 2131034131;
			
			// aapt resource value: 0x7f050015
			public const int rollc = 2131034133;
			
			// aapt resource value: 0x7f050018
			public const int rolledAOne = 2131034136;
			
			// aapt resource value: 0x7f050005
			public const int stNewGame = 2131034117;
			
			// aapt resource value: 0x7f050002
			public const int vsComp = 2131034114;
			
			// aapt resource value: 0x7f050003
			public const int vsPlayer = 2131034115;
			
			// aapt resource value: 0x7f050006
			public const int wins = 2131034118;
			
			// aapt resource value: 0x7f050019
			public const int youWon = 2131034137;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
