#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("com.xamarin.evolve2013.animationsdemo.Resource", IsApplication=true)]

namespace com.xamarin.evolve2013.animationsdemo
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues ();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int asteroid01 = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int asteroid02 = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int asteroid03 = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int asteroid04 = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int asteroid05 = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int asteroid06 = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int ic_action_info = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int ic_action_new = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int ic_action_photo = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int ic_launcher = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int ic_list_remove = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int image1 = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int image2 = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int ship2_2 = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int thumb1 = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int thumb2 = 2130837519;
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050000
			public const int container = 2131034112;
			
			// aapt resource value: 0x7f050003
			public const int expanded_image = 2131034115;
			
			// aapt resource value: 0x7f050001
			public const int thumb_button_1 = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int thumb_button_2 = 2131034114;
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int activity_zoom = 2130903040;
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040000
			public const int app_name = 2130968576;
			
			// aapt resource value: 0x7f04000c
			public const int description_image_1 = 2130968588;
			
			// aapt resource value: 0x7f04000d
			public const int description_image_2 = 2130968589;
			
			// aapt resource value: 0x7f04000e
			public const int description_zoom_touch_close = 2130968590;
			
			// aapt resource value: 0x7f04000b
			public const int message_shapedrawable = 2130968587;
			
			// aapt resource value: 0x7f04000a
			public const int message_zoom_touch_expand = 2130968586;
			
			// aapt resource value: 0x7f040001
			public const int title_animationdrawable = 2130968577;
			
			// aapt resource value: 0x7f040008
			public const int title_drawing = 2130968584;
			
			// aapt resource value: 0x7f040006
			public const int title_hyperspace = 2130968582;
			
			// aapt resource value: 0x7f040005
			public const int title_propertyanimation = 2130968581;
			
			// aapt resource value: 0x7f040007
			public const int title_setkarma = 2130968583;
			
			// aapt resource value: 0x7f040009
			public const int title_shapedrawables = 2130968585;
			
			// aapt resource value: 0x7f040002
			public const int title_spinasteroid = 2130968578;
			
			// aapt resource value: 0x7f040004
			public const int title_viewanimation = 2130968580;
			
			// aapt resource value: 0x7f040003
			public const int title_zoom = 2130968579;
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
