#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("PhonewordAndroid.Resource", IsApplication=true)]

namespace PhonewordAndroid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues ();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050003
			public const int Call = 2131034115;
			
			// aapt resource value: 0x7f050004
			public const int CallLogButton = 2131034116;
			
			// aapt resource value: 0x7f050001
			public const int PhoneNumberText = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int TranslateButton = 2131034114;
			
			// aapt resource value: 0x7f050000
			public const int textView1 = 2131034112;
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040003
			public const int Call = 2130968579;
			
			// aapt resource value: 0x7f040006
			public const int CallLogActivityLabel = 2130968582;
			
			// aapt resource value: 0x7f040005
			public const int CallLogButtonLabel = 2130968581;
			
			// aapt resource value: 0x7f040000
			public const int Enter = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int Number = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int Translate = 2130968578;
			
			// aapt resource value: 0x7f040004
			public const int app_name = 2130968580;
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
