//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace COINSMobile
{
	
	
	public partial class Resource
	{
		
		public partial class Attribute
		{
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f060003
			public const int deep_gray = 2131099651;
			
			// aapt resource value: 0x7f060001
			public const int light_gray = 2131099649;
			
			// aapt resource value: 0x7f060002
			public const int medium_gray = 2131099650;
			
			// aapt resource value: 0x7f060000
			public const int transparent = 2131099648;
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int home_icon = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int ic_market_watch = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int ic_quote_add = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int ic_stock_delete = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int ic_stock_get = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int Icon = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int icon_activity = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int refresh_icon = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int splash = 2130837512;
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f070013
			public const int button1D = 2131165203;
			
			// aapt resource value: 0x7f070017
			public const int button1Y = 2131165207;
			
			// aapt resource value: 0x7f070018
			public const int button2Y = 2131165208;
			
			// aapt resource value: 0x7f070015
			public const int button3M = 2131165205;
			
			// aapt resource value: 0x7f070014
			public const int button5D = 2131165204;
			
			// aapt resource value: 0x7f070019
			public const int button5Y = 2131165209;
			
			// aapt resource value: 0x7f070016
			public const int button6M = 2131165206;
			
			// aapt resource value: 0x7f070002
			public const int buttonAddStock = 2131165186;
			
			// aapt resource value: 0x7f070005
			public const int buttonGetStock = 2131165189;
			
			// aapt resource value: 0x7f07001d
			public const int buttonHome = 2131165213;
			
			// aapt resource value: 0x7f070007
			public const int buttonHomeget = 2131165191;
			
			// aapt resource value: 0x7f07001c
			public const int buttonRefresh = 2131165212;
			
			// aapt resource value: 0x7f070021
			public const int changecaption = 2131165217;
			
			// aapt resource value: 0x7f07000b
			public const int changecaptionget = 2131165195;
			
			// aapt resource value: 0x7f07001e
			public const int datetimecaption = 2131165214;
			
			// aapt resource value: 0x7f070008
			public const int datetimecaptionget = 2131165192;
			
			// aapt resource value: 0x7f070022
			public const int deatlLayout = 2131165218;
			
			// aapt resource value: 0x7f07000c
			public const int deatlLayoutget = 2131165196;
			
			// aapt resource value: 0x7f070011
			public const int deatlWatchLayout = 2131165201;
			
			// aapt resource value: 0x7f07001a
			public const int imageChart = 2131165210;
			
			// aapt resource value: 0x7f070000
			public const int linearLayout1 = 2131165184;
			
			// aapt resource value: 0x7f070003
			public const int linearLayoutGetstockdetails = 2131165187;
			
			// aapt resource value: 0x7f07000d
			public const int linearLayoutstockdetails = 2131165197;
			
			// aapt resource value: 0x7f070020
			public const int pricecaption = 2131165216;
			
			// aapt resource value: 0x7f07000a
			public const int pricecaptionget = 2131165194;
			
			// aapt resource value: 0x7f07001f
			public const int separator = 2131165215;
			
			// aapt resource value: 0x7f070009
			public const int separatorget = 2131165193;
			
			// aapt resource value: 0x7f070010
			public const int separatorwatch = 2131165200;
			
			// aapt resource value: 0x7f070012
			public const int stockchartcaption = 2131165202;
			
			// aapt resource value: 0x7f07001b
			public const int symbolcaption = 2131165211;
			
			// aapt resource value: 0x7f070006
			public const int symbolcaptiongetget = 2131165190;
			
			// aapt resource value: 0x7f070004
			public const int textGetStock = 2131165188;
			
			// aapt resource value: 0x7f070001
			public const int textStock = 2131165185;
			
			// aapt resource value: 0x7f07000f
			public const int watchRefresh = 2131165199;
			
			// aapt resource value: 0x7f07000e
			public const int watchcaption = 2131165198;
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int AddStock = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int GetStock = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int MarketWatch = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int ShowChart = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int StockDetails = 2130903044;
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int Aithor = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int ApplicationName = 2130968576;
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f050000
			public const int Theme_Splash = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int boldText = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int boldText19 = 2131034114;
			
			// aapt resource value: 0x7f050004
			public const int normalText = 2131034116;
			
			// aapt resource value: 0x7f050003
			public const int smallText = 2131034115;
			
			private Style()
			{
			}
		}
	}
}
