#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("AreaCalcFragDemo.Resource", IsApplication=true)]

namespace AreaCalcFragDemo
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int circle = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int Icon = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int rectangle = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int triangle = 2130837507;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f040005
			public const int calculateButton = 2130968581;
			
			// aapt resource value: 0x7f04000e
			public const int circleButton = 2130968590;
			
			// aapt resource value: 0x7f040001
			public const int diagramImageView = 2130968577;
			
			// aapt resource value: 0x7f040006
			public const int fragContainer1 = 2130968582;
			
			// aapt resource value: 0x7f040007
			public const int fragContainer2 = 2130968583;
			
			// aapt resource value: 0x7f04000a
			public const int heightEditText = 2130968586;
			
			// aapt resource value: 0x7f040008
			public const int linearLayout1 = 2130968584;
			
			// aapt resource value: 0x7f040002
			public const int linearLayout2 = 2130968578;
			
			// aapt resource value: 0x7f040004
			public const int radiusEditText = 2130968580;
			
			// aapt resource value: 0x7f04000c
			public const int rectangleButton = 2130968588;
			
			// aapt resource value: 0x7f04000f
			public const int resultTextView = 2130968591;
			
			// aapt resource value: 0x7f040009
			public const int textView1 = 2130968585;
			
			// aapt resource value: 0x7f040003
			public const int textView2 = 2130968579;
			
			// aapt resource value: 0x7f040000
			public const int textView3 = 2130968576;
			
			// aapt resource value: 0x7f04000d
			public const int triangleButton = 2130968589;
			
			// aapt resource value: 0x7f04000b
			public const int widthEditText = 2130968587;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int CircleFrag = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Main = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int RectangleFrag = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int SelectFrag = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int TriangleFrag = 2130903044;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
	}
}
#pragma warning restore 1591
