#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18033
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("HelloMultiScreen.Resource", IsApplication=true)]

namespace HelloMultiScreen
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int darwin = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int einstein = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int Icon = 2130837506;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050002
			public const int imageView1 = 2131034114;
			
			// aapt resource value: 0x7f050005
			public const int imageView2 = 2131034117;
			
			// aapt resource value: 0x7f050000
			public const int screen1Label = 2131034112;
			
			// aapt resource value: 0x7f050003
			public const int screen2Label = 2131034115;
			
			// aapt resource value: 0x7f050004
			public const int showFirst = 2131034116;
			
			// aapt resource value: 0x7f050001
			public const int showSecond = 2131034113;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Second = 2130903041;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040000
			public const int app_name = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int firstActButtonText = 2130968577;
			
			// aapt resource value: 0x7f040009
			public const int nm = 2130968585;
			
			// aapt resource value: 0x7f040007
			public const int noData = 2130968583;
			
			// aapt resource value: 0x7f040005
			public const int poke1 = 2130968581;
			
			// aapt resource value: 0x7f040006
			public const int poke2 = 2130968582;
			
			// aapt resource value: 0x7f040003
			public const int screen1Text = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int screen2Text = 2130968580;
			
			// aapt resource value: 0x7f040002
			public const int secondActButtonText = 2130968578;
			
			// aapt resource value: 0x7f040008
			public const int stopIt = 2130968584;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
