#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.32559
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("PigAndroid.Resource", IsApplication=true)]

namespace PigAndroid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Die1 = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int Die2 = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int Die3 = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int Die4 = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int Die5 = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int Die6 = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int Icon = 2130837510;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050008
			public const int P1HoldButton = 2131034120;
			
			// aapt resource value: 0x7f050009
			public const int P1InfoText = 2131034121;
			
			// aapt resource value: 0x7f05000a
			public const int P1RollButton = 2131034122;
			
			// aapt resource value: 0x7f05000b
			public const int P2HoldButton = 2131034123;
			
			// aapt resource value: 0x7f05000c
			public const int P2InfoText = 2131034124;
			
			// aapt resource value: 0x7f05000d
			public const int P2RollButton = 2131034125;
			
			// aapt resource value: 0x7f050001
			public const int Player1ComputerBox = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int Player1Text = 2131034112;
			
			// aapt resource value: 0x7f050003
			public const int Player2ComputerBox = 2131034115;
			
			// aapt resource value: 0x7f050002
			public const int Player2Text = 2131034114;
			
			// aapt resource value: 0x7f050005
			public const int ScoreSheetPlayer1 = 2131034117;
			
			// aapt resource value: 0x7f050006
			public const int ScoreSheetPlayer2 = 2131034118;
			
			// aapt resource value: 0x7f050004
			public const int StartGame = 2131034116;
			
			// aapt resource value: 0x7f05000e
			public const int listView1 = 2131034126;
			
			// aapt resource value: 0x7f050007
			public const int textviewMainInfo = 2131034119;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int GameTab = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Main = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int PlayerTab = 2130903042;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040000
			public const int app_name = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
