#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("PigGame.Resource", IsApplication=true)]

namespace PigGame
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7f040000
			public const int NumberOfDieSpinnerArray = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int die_numbers_array = 2130968577;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int artwork = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int cupped_hands = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int dice_icon = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int Die1 = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int Die2 = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int Die3 = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int Die4 = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int Die5 = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int Die6 = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int FullDice = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int gears = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int ic_tab_artists = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int ic_tab_artists_grey = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int ic_tab_artists_white = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int Icon = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int start = 2130837519;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060012
			public const int Commit = 2131099666;
			
			// aapt resource value: 0x7f060004
			public const int GameLabel = 2131099652;
			
			// aapt resource value: 0x7f060008
			public const int SettingsHeader = 2131099656;
			
			// aapt resource value: 0x7f060007
			public const int StartButton = 2131099655;
			
			// aapt resource value: 0x7f060013
			public const int Summary = 2131099667;
			
			// aapt resource value: 0x7f060003
			public const int backToFirst = 2131099651;
			
			// aapt resource value: 0x7f060001
			public const int dataText = 2131099649;
			
			// aapt resource value: 0x7f060000
			public const int dieRollButton = 2131099648;
			
			// aapt resource value: 0x7f060014
			public const int die_prompt = 2131099668;
			
			// aapt resource value: 0x7f06000a
			public const int disclaimer = 2131099658;
			
			// aapt resource value: 0x7f060002
			public const int endTurnButton = 2131099650;
			
			// aapt resource value: 0x7f060005
			public const int gamePlaysText = 2131099653;
			
			// aapt resource value: 0x7f060010
			public const int inputText = 2131099664;
			
			// aapt resource value: 0x7f06000c
			public const int numberofDies = 2131099660;
			
			// aapt resource value: 0x7f060006
			public const int playerWinsText = 2131099654;
			
			// aapt resource value: 0x7f06000d
			public const int radioButton1 = 2131099661;
			
			// aapt resource value: 0x7f06000e
			public const int radioButton2 = 2131099662;
			
			// aapt resource value: 0x7f06000f
			public const int radioButton3 = 2131099663;
			
			// aapt resource value: 0x7f060015
			public const int radiogroup = 2131099669;
			
			// aapt resource value: 0x7f06000b
			public const int radiotext = 2131099659;
			
			// aapt resource value: 0x7f060011
			public const int scoreinput = 2131099665;
			
			// aapt resource value: 0x7f060009
			public const int spinner = 2131099657;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Game = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Main = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Menu = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Settings = 2130903043;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050000
			public const int ApplicationName = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int Data = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int EndButton = 2131034114;
			
			// aapt resource value: 0x7f050005
			public const int GameLabel = 2131034117;
			
			// aapt resource value: 0x7f05000c
			public const int InputPrompt = 2131034124;
			
			// aapt resource value: 0x7f05000b
			public const int NumberofDieRadioText = 2131034123;
			
			// aapt resource value: 0x7f05000d
			public const int commit = 2131034125;
			
			// aapt resource value: 0x7f050004
			public const int countLabel = 2131034116;
			
			// aapt resource value: 0x7f050009
			public const int die_prompt = 2131034121;
			
			// aapt resource value: 0x7f05000a
			public const int disclaimer = 2131034122;
			
			// aapt resource value: 0x7f050006
			public const int doneButton = 2131034118;
			
			// aapt resource value: 0x7f050008
			public const int number_of_die_to_roll = 2131034120;
			
			// aapt resource value: 0x7f050007
			public const int settingsHeader = 2131034119;
			
			// aapt resource value: 0x7f050003
			public const int winLabel = 2131034115;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
