// This file has been autogenerated from parsing an Objective-C header file added in Xcode.

using System;

using MonoTouch.Foundation;
using MonoTouch.UIKit;

namespace StoryboardDemo
{
	public partial class SecondController : UIViewController
	{
		public SecondController (IntPtr handle) : base (handle)
		{
		}
	}
}
