#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("EvolveLite.Resource", IsApplication=true)]

namespace EvolveLite
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues ();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int ic_launcher = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int ic_menu_refresh_data = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int ic_menu_take_picture = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int ic_menu_twitter = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int ic_tab_my_schedule = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int ic_tab_my_schedule_selected = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int ic_tab_my_schedule_unselected = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int ic_tab_photos = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int ic_tab_photos_selected = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int ic_tab_photos_unselected = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int ic_tab_sessions = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int ic_tab_sessions_selected = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int ic_tab_sessions_unselected = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int ic_tab_speakers = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int ic_tab_speakers_selected = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int ic_tab_speakers_unselected = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int ic_tab_whats_on = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int ic_tab_whats_on_selected = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int ic_tab_whats_on_unselected = 2130837522;
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f070002
			public const int gridView = 2131165186;
			
			// aapt resource value: 0x7f070000
			public const int heading = 2131165184;
			
			// aapt resource value: 0x7f070003
			public const int menu_apply_filter = 2131165187;
			
			// aapt resource value: 0x7f070004
			public const int menu_delete_picture = 2131165188;
			
			// aapt resource value: 0x7f070006
			public const int menu_take_picture = 2131165190;
			
			// aapt resource value: 0x7f070005
			public const int menu_tweet_picture = 2131165189;
			
			// aapt resource value: 0x7f070001
			public const int takePhoto = 2131165185;
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Photos = 2130903041;
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f060000
			public const int photo_context_menu = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int photosactivity_menu = 2131099649;
			
			private Menu()
			{
			}
		}
		
		public partial class Plurals
		{
			
			// aapt resource value: 0x7f050000
			public const int speaker_sessions = 2131034112;
			
			private Plurals()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040004
			public const int activity_my_schedule_label = 2130968580;
			
			// aapt resource value: 0x7f040005
			public const int activity_photos_label = 2130968581;
			
			// aapt resource value: 0x7f040002
			public const int activity_sessions_label = 2130968578;
			
			// aapt resource value: 0x7f040001
			public const int activity_speakers_label = 2130968577;
			
			// aapt resource value: 0x7f040003
			public const int activity_whats_on_label = 2130968579;
			
			// aapt resource value: 0x7f040000
			public const int app_name = 2130968576;
			
			// aapt resource value: 0x7f04000e
			public const int apply_sepia_filter_done = 2130968590;
			
			// aapt resource value: 0x7f04000d
			public const int apply_sepia_filter_message = 2130968589;
			
			// aapt resource value: 0x7f04000c
			public const int apply_sepia_filter_title = 2130968588;
			
			// aapt resource value: 0x7f04000f
			public const int camera_not_available = 2130968591;
			
			// aapt resource value: 0x7f040010
			public const int downloading_sessions_json_message = 2130968592;
			
			// aapt resource value: 0x7f040011
			public const int downloading_sessions_json_title = 2130968593;
			
			// aapt resource value: 0x7f040012
			public const int loading_sessions_json_message = 2130968594;
			
			// aapt resource value: 0x7f040013
			public const int loading_sessions_json_title = 2130968595;
			
			// aapt resource value: 0x7f040006
			public const int menu_apply_filter = 2130968582;
			
			// aapt resource value: 0x7f040007
			public const int menu_authenticate_twitter = 2130968583;
			
			// aapt resource value: 0x7f040008
			public const int menu_delete_picture = 2130968584;
			
			// aapt resource value: 0x7f040009
			public const int menu_refresh_data = 2130968585;
			
			// aapt resource value: 0x7f04000a
			public const int menu_share_with_twitter = 2130968586;
			
			// aapt resource value: 0x7f04000b
			public const int menu_take_picture = 2130968587;
			
			// aapt resource value: 0x7f040014
			public const int no_twitter_client = 2130968596;
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
